---
- hosts: node
  tasks:
  - name: Check that a web server based in docker container returns a status 200
    shell: "curl 192.168.182.3:81"
#    shell: "curl -Is 192.168.182.3:81 | head -1" HTTP 200 OK ONLY
    register: result
  - debug: var=result
