---
- hosts: node
  vars:
    result:
  tasks:
  - name: Check that a web server based in docker container returns a status 200
    shell: 'curl -Is 192.168.182.3:81 | head -1'
#    register: result
#  - debug: var=result
#  - name: Output of the result
#    shell: "sleep 5"
