---
- hosts: node
  tasks:
#  - name: Check that a web server based in docker container returns a status 200
#    uri:
#      url: http://192.168.182.3:81/
#      return_content: yes
#    register: this
#    failed_when: "'AWESOME' not in this.content"
    shell: "echo $(curl -Is 192.168.182.3:81 | head -1) "
#    register: result
#  - debug: var=result
#  - name: Output of the result
#    shell: "sleep 5"
