#tasks for roles/web-app-role
- name: Login to Docker Hub
  docker_login:
    username: "minisheriff"
    password: "{{ dockerhub_pass }}"
- name: Create docker network
  docker_network:
    name: balancenet
- name: launch 1st container (port 5001)
  docker_container:
    image: "minisheriff/cicd-exam:p3"
    name: "web-app-1"
    networks: balancenet
    hostname: w1.local
    ports:
      5001:5000
- name: launch 2nd container (port 5002)
  docker_container:
    image: "minisheriff/cicd-exam:p3"
    name: "web-app-2"
    networks: balancenet
    hostname: w2.local
    ports:
      5002:5000
- name: launch 3rd container (port 5003)
  docker_container:
    image: "minisheriff/cicd-exam:p3"
    name: "web-app-3"
    networks: balancenet
    hostname: w3.local
    ports:
      5003:5000